# Generated by Django 4.2 on 2025-01-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='court',
            name='available_days',
            field=models.CharField(default='1234567', help_text='1=Lunes, 2=Martes, etc.', max_length=7, verbose_name='Días disponibles'),
        ),
        migrations.AddField(
            model_name='court',
            name='closing_time',
            field=models.TimeField(default='22:00', verbose_name='Hora de cierre'),
        ),
        migrations.AddField(
            model_name='court',
            name='opening_time',
            field=models.TimeField(default='07:00', verbose_name='Hora de apertura'),
        ),
    ]
