# Generated by Django 4.2 on 2025-01-13 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_court_available_days_court_closing_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RESERVATION_CREATED', 'Reserva creada'), ('PAYMENT_CONFIRMED', 'Pago confirmado'), ('RESERVATION_REMINDER', 'Recordatorio de reserva'), ('STATUS_CHANGE', 'Cambio de estado')], max_length=20, verbose_name='Tipo')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('sent_via_whatsapp', models.BooleanField(default=False, verbose_name='Enviado por WhatsApp')),
                ('sent_via_email', models.BooleanField(default=False, verbose_name='Enviado por Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
