# Generated by Django 4.2 on 2025-01-14 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_payment_options_payment_bank_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='bank',
            field=models.CharField(blank=True, choices=[('BANCO1', 'Banco 1'), ('BANCO2', 'Banco 2'), ('BANCO3', 'Banco 3'), ('BANCO4', 'Banco 4'), ('BANCO5', 'Banco 5')], max_length=20, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de teléfono'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_last_digits',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Últimos 4 dígitos de referencia'),
        ),
    ]
