# Generated by Django 4.2 on 2025-01-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_payment_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='zelle_email',
            field=models.EmailField(blank=True, help_text='Email de la cuenta Zelle que realizó el pago', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='zelle_holder',
            field=models.CharField(blank=True, help_text='Nombre del titular de la cuenta Zelle', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('CARD', 'Tarjeta'), ('PAGOMOVIL', 'Pago Móvil'), ('ZELLE', 'Zelle')], default='CARD', max_length=20),
        ),
    ]
