name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            echo "Starting deployment..."
            cd /var/www/arenaspadel
            echo "Pulling latest changes..."
            git pull
            echo "Activating virtual environment..."
            source venv/bin/activate
            echo "Installing requirements..."
            pip install -r requirements.txt
            echo "Setting up environment variables..."
            echo "DB_NAME=arenaspadel" > .env
            echo "DB_USER=arenaspadel_user" >> .env
            echo "DB_PASSWORD=1ArenasPadel9906" >> .env
            echo "DB_HOST=localhost" >> .env
            echo "DB_PORT=5432" >> .env
            echo "STRIPE_PUBLIC_KEY=pk_test_your_key" >> .env
            echo "STRIPE_SECRET_KEY=sk_test_your_key" >> .env
            echo "Running migrations..."
            python manage.py migrate
            echo "Restarting Gunicorn..."
            sudo systemctl restart gunicorn || true
            echo "Deployment complete!"