name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            echo "Starting deployment..."
            cd /var/www/arenaspadel
            echo "Pulling latest changes..."
            git pull
            echo "Activating virtual environment..."
            source venv/bin/activate
            echo "Installing requirements..."
            pip install -r requirements.txt
            echo "Setting up environment variables..."
            echo "DB_NAME=arenaspadel" > .env
            echo "DB_USER=arenaspadel_user" >> .env
            echo "DB_PASSWORD=1ArenasPadel9906" >> .env
            echo "DB_HOST=localhost" >> .env
            echo "DB_PORT=5432" >> .env
            echo "STRIPE_PUBLIC_KEY=pk_test_51MeV01HizWn3jHF5ZCGkCFyDwqNdCQaJo5HPaXwRdnDbu2qmiP0Oj2qqzscHU6JcPnpZJlFIbq198XE2sxshKAvb000NH8tlKt" >> .env
            echo "STRIPE_SECRET_KEY=sk_test_51MeV01HizWn3jHF5qBAVXwReGfvUGQpIFTPqWWWtxiSi6b99FDrpHBFXdBzYkIj5p3gKVTWdVd4QNBD9sjTLbDZV00aigyXYo6" >> .env

            echo "Running migrations..."
            python manage.py migrate

            echo "Configuring Gunicorn service..."
            sudo bash -c 'cat > /etc/systemd/system/gunicorn.service << "EOF"
            [Unit]
            Description=Gunicorn daemon for Arenas Padel
            After=network.target

            [Service]
            User=root
            Group=www-data
            WorkingDirectory=/var/www/arenaspadel
            ExecStart=/var/www/arenaspadel/venv/bin/gunicorn --workers 3 --bind unix:/var/www/arenaspadel/arenaspadel.sock config.wsgi:application

            [Install]
            WantedBy=multi-user.target
            EOF'

            echo "Reloading systemd..."
            sudo systemctl daemon-reload
            echo "Starting Gunicorn..."
            sudo systemctl enable gunicorn
            sudo systemctl restart gunicorn
            echo "Deployment complete!"