name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            echo "Starting deployment..."
            cd /var/www/arenaspadel
            echo "Pulling latest changes..."
            git pull
            echo "Activating virtual environment..."
            source venv/bin/activate
            echo "Installing requirements..."
            pip install -r requirements.txt
            echo "Running migrations..."
            python manage.py migrate
            echo "Restarting Gunicorn..."
            sudo systemctl restart gunicorn
            echo "Deployment complete!" 